// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_INCLUDED_common_2eproto
#define PROTOBUF_INCLUDED_common_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_common_2eproto 

namespace protobuf_common_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_common_2eproto
namespace bumoProtocol {
class KeyPair;
class KeyPairDefaultTypeInternal;
extern KeyPairDefaultTypeInternal _KeyPair_default_instance_;
class LedgerUpgrade;
class LedgerUpgradeDefaultTypeInternal;
extern LedgerUpgradeDefaultTypeInternal _LedgerUpgrade_default_instance_;
class Ping;
class PingDefaultTypeInternal;
extern PingDefaultTypeInternal _Ping_default_instance_;
class Pong;
class PongDefaultTypeInternal;
extern PongDefaultTypeInternal _Pong_default_instance_;
class Signature;
class SignatureDefaultTypeInternal;
extern SignatureDefaultTypeInternal _Signature_default_instance_;
class WsMessage;
class WsMessageDefaultTypeInternal;
extern WsMessageDefaultTypeInternal _WsMessage_default_instance_;
}  // namespace bumoProtocol
namespace google {
namespace protobuf {
template<> ::bumoProtocol::KeyPair* Arena::CreateMaybeMessage<::bumoProtocol::KeyPair>(Arena*);
template<> ::bumoProtocol::LedgerUpgrade* Arena::CreateMaybeMessage<::bumoProtocol::LedgerUpgrade>(Arena*);
template<> ::bumoProtocol::Ping* Arena::CreateMaybeMessage<::bumoProtocol::Ping>(Arena*);
template<> ::bumoProtocol::Pong* Arena::CreateMaybeMessage<::bumoProtocol::Pong>(Arena*);
template<> ::bumoProtocol::Signature* Arena::CreateMaybeMessage<::bumoProtocol::Signature>(Arena*);
template<> ::bumoProtocol::WsMessage* Arena::CreateMaybeMessage<::bumoProtocol::WsMessage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace bumoProtocol {

enum ERRORCODE {
  ERRCODE_SUCCESS = 0,
  ERRCODE_INTERNAL_ERROR = 1,
  ERRCODE_INVALID_PARAMETER = 2,
  ERRCODE_ALREADY_EXIST = 3,
  ERRCODE_NOT_EXIST = 4,
  ERRCODE_TX_TIMEOUT = 5,
  ERRCODE_ACCESS_DENIED = 6,
  ERRCODE_MATH_OVERFLOW = 7,
  ERRCODE_EXPR_CONDITION_RESULT_FALSE = 20,
  ERRCODE_EXPR_CONDITION_SYNTAX_ERROR = 21,
  ERRCODE_INVALID_PUBKEY = 90,
  ERRCODE_INVALID_PRIKEY = 91,
  ERRCODE_ASSET_INVALID = 92,
  ERRCODE_INVALID_SIGNATURE = 93,
  ERRCODE_INVALID_ADDRESS = 94,
  ERRCODE_MISSING_OPERATIONS = 97,
  ERRCODE_TOO_MANY_OPERATIONS = 98,
  ERRCODE_BAD_SEQUENCE = 99,
  ERRCODE_ACCOUNT_LOW_RESERVE = 100,
  ERRCODE_ACCOUNT_SOURCEDEST_EQUAL = 101,
  ERRCODE_ACCOUNT_DEST_EXIST = 102,
  ERRCODE_ACCOUNT_NOT_EXIST = 103,
  ERRCODE_ACCOUNT_ASSET_LOW_RESERVE = 104,
  ERRCODE_ACCOUNT_ASSET_AMOUNT_TOO_LARGE = 105,
  ERRCODE_ACCOUNT_INIT_LOW_RESERVE = 106,
  ERRCODE_FEE_NOT_ENOUGH = 111,
  ERRCODE_FEE_INVALID = 112,
  ERRCODE_OUT_OF_TXCACHE = 114,
  ERRCODE_WEIGHT_NOT_VALID = 120,
  ERRCODE_THRESHOLD_NOT_VALID = 121,
  ERRCODE_INVALID_DATAVERSION = 144,
  ERRCODE_TX_SIZE_TOO_BIG = 146,
  ERRCODE_CONTRACT_EXECUTE_FAIL = 151,
  ERRCODE_CONTRACT_SYNTAX_ERROR = 152,
  ERRCODE_CONTRACT_TOO_MANY_RECURSION = 153,
  ERRCODE_CONTRACT_TOO_MANY_TRANSACTIONS = 154,
  ERRCODE_CONTRACT_EXECUTE_EXPIRED = 155,
  ERRCODE_TX_INSERT_QUEUE_FAIL = 160,
  ERRORCODE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ERRORCODE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ERRORCODE_IsValid(int value);
const ERRORCODE ERRORCODE_MIN = ERRCODE_SUCCESS;
const ERRORCODE ERRORCODE_MAX = ERRCODE_TX_INSERT_QUEUE_FAIL;
const int ERRORCODE_ARRAYSIZE = ERRORCODE_MAX + 1;

const ::google::protobuf::EnumDescriptor* ERRORCODE_descriptor();
inline const ::std::string& ERRORCODE_Name(ERRORCODE value) {
  return ::google::protobuf::internal::NameOfEnum(
    ERRORCODE_descriptor(), value);
}
inline bool ERRORCODE_Parse(
    const ::std::string& name, ERRORCODE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ERRORCODE>(
    ERRORCODE_descriptor(), name, value);
}
// ===================================================================

class KeyPair : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bumoProtocol.KeyPair) */ {
 public:
  KeyPair();
  virtual ~KeyPair();

  KeyPair(const KeyPair& from);

  inline KeyPair& operator=(const KeyPair& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KeyPair(KeyPair&& from) noexcept
    : KeyPair() {
    *this = ::std::move(from);
  }

  inline KeyPair& operator=(KeyPair&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyPair& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyPair* internal_default_instance() {
    return reinterpret_cast<const KeyPair*>(
               &_KeyPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(KeyPair* other);
  friend void swap(KeyPair& a, KeyPair& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KeyPair* New() const final {
    return CreateMaybeMessage<KeyPair>(NULL);
  }

  KeyPair* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KeyPair>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const KeyPair& from);
  void MergeFrom(const KeyPair& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyPair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // int64 version = 3;
  void clear_version();
  static const int kVersionFieldNumber = 3;
  ::google::protobuf::int64 version() const;
  void set_version(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:bumoProtocol.KeyPair)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::int64 version_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Signature : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bumoProtocol.Signature) */ {
 public:
  Signature();
  virtual ~Signature();

  Signature(const Signature& from);

  inline Signature& operator=(const Signature& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Signature(Signature&& from) noexcept
    : Signature() {
    *this = ::std::move(from);
  }

  inline Signature& operator=(Signature&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Signature& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Signature* internal_default_instance() {
    return reinterpret_cast<const Signature*>(
               &_Signature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Signature* other);
  friend void swap(Signature& a, Signature& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Signature* New() const final {
    return CreateMaybeMessage<Signature>(NULL);
  }

  Signature* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Signature>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Signature& from);
  void MergeFrom(const Signature& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Signature* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string public_key = 1;
  void clear_public_key();
  static const int kPublicKeyFieldNumber = 1;
  const ::std::string& public_key() const;
  void set_public_key(const ::std::string& value);
  #if LANG_CXX11
  void set_public_key(::std::string&& value);
  #endif
  void set_public_key(const char* value);
  void set_public_key(const char* value, size_t size);
  ::std::string* mutable_public_key();
  ::std::string* release_public_key();
  void set_allocated_public_key(::std::string* public_key);

  // bytes sign_data = 2;
  void clear_sign_data();
  static const int kSignDataFieldNumber = 2;
  const ::std::string& sign_data() const;
  void set_sign_data(const ::std::string& value);
  #if LANG_CXX11
  void set_sign_data(::std::string&& value);
  #endif
  void set_sign_data(const char* value);
  void set_sign_data(const void* value, size_t size);
  ::std::string* mutable_sign_data();
  ::std::string* release_sign_data();
  void set_allocated_sign_data(::std::string* sign_data);

  // @@protoc_insertion_point(class_scope:bumoProtocol.Signature)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr public_key_;
  ::google::protobuf::internal::ArenaStringPtr sign_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LedgerUpgrade : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bumoProtocol.LedgerUpgrade) */ {
 public:
  LedgerUpgrade();
  virtual ~LedgerUpgrade();

  LedgerUpgrade(const LedgerUpgrade& from);

  inline LedgerUpgrade& operator=(const LedgerUpgrade& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LedgerUpgrade(LedgerUpgrade&& from) noexcept
    : LedgerUpgrade() {
    *this = ::std::move(from);
  }

  inline LedgerUpgrade& operator=(LedgerUpgrade&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LedgerUpgrade& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LedgerUpgrade* internal_default_instance() {
    return reinterpret_cast<const LedgerUpgrade*>(
               &_LedgerUpgrade_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(LedgerUpgrade* other);
  friend void swap(LedgerUpgrade& a, LedgerUpgrade& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LedgerUpgrade* New() const final {
    return CreateMaybeMessage<LedgerUpgrade>(NULL);
  }

  LedgerUpgrade* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LedgerUpgrade>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LedgerUpgrade& from);
  void MergeFrom(const LedgerUpgrade& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LedgerUpgrade* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string new_validator = 2;
  void clear_new_validator();
  static const int kNewValidatorFieldNumber = 2;
  const ::std::string& new_validator() const;
  void set_new_validator(const ::std::string& value);
  #if LANG_CXX11
  void set_new_validator(::std::string&& value);
  #endif
  void set_new_validator(const char* value);
  void set_new_validator(const char* value, size_t size);
  ::std::string* mutable_new_validator();
  ::std::string* release_new_validator();
  void set_allocated_new_validator(::std::string* new_validator);

  // int64 new_ledger_version = 1;
  void clear_new_ledger_version();
  static const int kNewLedgerVersionFieldNumber = 1;
  ::google::protobuf::int64 new_ledger_version() const;
  void set_new_ledger_version(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:bumoProtocol.LedgerUpgrade)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr new_validator_;
  ::google::protobuf::int64 new_ledger_version_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class WsMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bumoProtocol.WsMessage) */ {
 public:
  WsMessage();
  virtual ~WsMessage();

  WsMessage(const WsMessage& from);

  inline WsMessage& operator=(const WsMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WsMessage(WsMessage&& from) noexcept
    : WsMessage() {
    *this = ::std::move(from);
  }

  inline WsMessage& operator=(WsMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const WsMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WsMessage* internal_default_instance() {
    return reinterpret_cast<const WsMessage*>(
               &_WsMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(WsMessage* other);
  friend void swap(WsMessage& a, WsMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WsMessage* New() const final {
    return CreateMaybeMessage<WsMessage>(NULL);
  }

  WsMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WsMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WsMessage& from);
  void MergeFrom(const WsMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WsMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 4;
  void clear_data();
  static const int kDataFieldNumber = 4;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // int64 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int64 type() const;
  void set_type(::google::protobuf::int64 value);

  // int64 sequence = 3;
  void clear_sequence();
  static const int kSequenceFieldNumber = 3;
  ::google::protobuf::int64 sequence() const;
  void set_sequence(::google::protobuf::int64 value);

  // bool request = 2;
  void clear_request();
  static const int kRequestFieldNumber = 2;
  bool request() const;
  void set_request(bool value);

  // @@protoc_insertion_point(class_scope:bumoProtocol.WsMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int64 type_;
  ::google::protobuf::int64 sequence_;
  bool request_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Ping : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bumoProtocol.Ping) */ {
 public:
  Ping();
  virtual ~Ping();

  Ping(const Ping& from);

  inline Ping& operator=(const Ping& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ping(Ping&& from) noexcept
    : Ping() {
    *this = ::std::move(from);
  }

  inline Ping& operator=(Ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ping* internal_default_instance() {
    return reinterpret_cast<const Ping*>(
               &_Ping_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Ping* other);
  friend void swap(Ping& a, Ping& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ping* New() const final {
    return CreateMaybeMessage<Ping>(NULL);
  }

  Ping* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Ping>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Ping& from);
  void MergeFrom(const Ping& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 nonce = 1;
  void clear_nonce();
  static const int kNonceFieldNumber = 1;
  ::google::protobuf::int64 nonce() const;
  void set_nonce(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:bumoProtocol.Ping)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 nonce_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_common_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Pong : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bumoProtocol.Pong) */ {
 public:
  Pong();
  virtual ~Pong();

  Pong(const Pong& from);

  inline Pong& operator=(const Pong& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Pong(Pong&& from) noexcept
    : Pong() {
    *this = ::std::move(from);
  }

  inline Pong& operator=(Pong&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Pong& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Pong* internal_default_instance() {
    return reinterpret_cast<const Pong*>(
               &_Pong_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Pong* other);
  friend void swap(Pong& a, Pong& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Pong* New() const final {
    return CreateMaybeMessage<Pong>(NULL);
  }

  Pong* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Pong>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Pong& from);
  void MergeFrom(const Pong& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Pong* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 nonce = 1;
  void clear_nonce();
  static const int kNonceFieldNumber = 1;
  ::google::protobuf::int64 nonce() const;
  void set_nonce(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:bumoProtocol.Pong)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 nonce_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_common_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KeyPair

// string key = 1;
inline void KeyPair::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KeyPair::key() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.KeyPair.key)
  return key_.GetNoArena();
}
inline void KeyPair::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bumoProtocol.KeyPair.key)
}
#if LANG_CXX11
inline void KeyPair::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bumoProtocol.KeyPair.key)
}
#endif
inline void KeyPair::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bumoProtocol.KeyPair.key)
}
inline void KeyPair::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bumoProtocol.KeyPair.key)
}
inline ::std::string* KeyPair::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:bumoProtocol.KeyPair.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KeyPair::release_key() {
  // @@protoc_insertion_point(field_release:bumoProtocol.KeyPair.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KeyPair::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:bumoProtocol.KeyPair.key)
}

// string value = 2;
inline void KeyPair::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KeyPair::value() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.KeyPair.value)
  return value_.GetNoArena();
}
inline void KeyPair::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bumoProtocol.KeyPair.value)
}
#if LANG_CXX11
inline void KeyPair::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bumoProtocol.KeyPair.value)
}
#endif
inline void KeyPair::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bumoProtocol.KeyPair.value)
}
inline void KeyPair::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bumoProtocol.KeyPair.value)
}
inline ::std::string* KeyPair::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:bumoProtocol.KeyPair.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KeyPair::release_value() {
  // @@protoc_insertion_point(field_release:bumoProtocol.KeyPair.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KeyPair::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:bumoProtocol.KeyPair.value)
}

// int64 version = 3;
inline void KeyPair::clear_version() {
  version_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 KeyPair::version() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.KeyPair.version)
  return version_;
}
inline void KeyPair::set_version(::google::protobuf::int64 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:bumoProtocol.KeyPair.version)
}

// -------------------------------------------------------------------

// Signature

// string public_key = 1;
inline void Signature::clear_public_key() {
  public_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Signature::public_key() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.Signature.public_key)
  return public_key_.GetNoArena();
}
inline void Signature::set_public_key(const ::std::string& value) {
  
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bumoProtocol.Signature.public_key)
}
#if LANG_CXX11
inline void Signature::set_public_key(::std::string&& value) {
  
  public_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bumoProtocol.Signature.public_key)
}
#endif
inline void Signature::set_public_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bumoProtocol.Signature.public_key)
}
inline void Signature::set_public_key(const char* value, size_t size) {
  
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bumoProtocol.Signature.public_key)
}
inline ::std::string* Signature::mutable_public_key() {
  
  // @@protoc_insertion_point(field_mutable:bumoProtocol.Signature.public_key)
  return public_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Signature::release_public_key() {
  // @@protoc_insertion_point(field_release:bumoProtocol.Signature.public_key)
  
  return public_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Signature::set_allocated_public_key(::std::string* public_key) {
  if (public_key != NULL) {
    
  } else {
    
  }
  public_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), public_key);
  // @@protoc_insertion_point(field_set_allocated:bumoProtocol.Signature.public_key)
}

// bytes sign_data = 2;
inline void Signature::clear_sign_data() {
  sign_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Signature::sign_data() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.Signature.sign_data)
  return sign_data_.GetNoArena();
}
inline void Signature::set_sign_data(const ::std::string& value) {
  
  sign_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bumoProtocol.Signature.sign_data)
}
#if LANG_CXX11
inline void Signature::set_sign_data(::std::string&& value) {
  
  sign_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bumoProtocol.Signature.sign_data)
}
#endif
inline void Signature::set_sign_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sign_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bumoProtocol.Signature.sign_data)
}
inline void Signature::set_sign_data(const void* value, size_t size) {
  
  sign_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bumoProtocol.Signature.sign_data)
}
inline ::std::string* Signature::mutable_sign_data() {
  
  // @@protoc_insertion_point(field_mutable:bumoProtocol.Signature.sign_data)
  return sign_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Signature::release_sign_data() {
  // @@protoc_insertion_point(field_release:bumoProtocol.Signature.sign_data)
  
  return sign_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Signature::set_allocated_sign_data(::std::string* sign_data) {
  if (sign_data != NULL) {
    
  } else {
    
  }
  sign_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sign_data);
  // @@protoc_insertion_point(field_set_allocated:bumoProtocol.Signature.sign_data)
}

// -------------------------------------------------------------------

// LedgerUpgrade

// int64 new_ledger_version = 1;
inline void LedgerUpgrade::clear_new_ledger_version() {
  new_ledger_version_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LedgerUpgrade::new_ledger_version() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.LedgerUpgrade.new_ledger_version)
  return new_ledger_version_;
}
inline void LedgerUpgrade::set_new_ledger_version(::google::protobuf::int64 value) {
  
  new_ledger_version_ = value;
  // @@protoc_insertion_point(field_set:bumoProtocol.LedgerUpgrade.new_ledger_version)
}

// string new_validator = 2;
inline void LedgerUpgrade::clear_new_validator() {
  new_validator_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LedgerUpgrade::new_validator() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.LedgerUpgrade.new_validator)
  return new_validator_.GetNoArena();
}
inline void LedgerUpgrade::set_new_validator(const ::std::string& value) {
  
  new_validator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bumoProtocol.LedgerUpgrade.new_validator)
}
#if LANG_CXX11
inline void LedgerUpgrade::set_new_validator(::std::string&& value) {
  
  new_validator_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bumoProtocol.LedgerUpgrade.new_validator)
}
#endif
inline void LedgerUpgrade::set_new_validator(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  new_validator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bumoProtocol.LedgerUpgrade.new_validator)
}
inline void LedgerUpgrade::set_new_validator(const char* value, size_t size) {
  
  new_validator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bumoProtocol.LedgerUpgrade.new_validator)
}
inline ::std::string* LedgerUpgrade::mutable_new_validator() {
  
  // @@protoc_insertion_point(field_mutable:bumoProtocol.LedgerUpgrade.new_validator)
  return new_validator_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LedgerUpgrade::release_new_validator() {
  // @@protoc_insertion_point(field_release:bumoProtocol.LedgerUpgrade.new_validator)
  
  return new_validator_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LedgerUpgrade::set_allocated_new_validator(::std::string* new_validator) {
  if (new_validator != NULL) {
    
  } else {
    
  }
  new_validator_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), new_validator);
  // @@protoc_insertion_point(field_set_allocated:bumoProtocol.LedgerUpgrade.new_validator)
}

// -------------------------------------------------------------------

// WsMessage

// int64 type = 1;
inline void WsMessage::clear_type() {
  type_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 WsMessage::type() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.WsMessage.type)
  return type_;
}
inline void WsMessage::set_type(::google::protobuf::int64 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:bumoProtocol.WsMessage.type)
}

// bool request = 2;
inline void WsMessage::clear_request() {
  request_ = false;
}
inline bool WsMessage::request() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.WsMessage.request)
  return request_;
}
inline void WsMessage::set_request(bool value) {
  
  request_ = value;
  // @@protoc_insertion_point(field_set:bumoProtocol.WsMessage.request)
}

// int64 sequence = 3;
inline void WsMessage::clear_sequence() {
  sequence_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 WsMessage::sequence() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.WsMessage.sequence)
  return sequence_;
}
inline void WsMessage::set_sequence(::google::protobuf::int64 value) {
  
  sequence_ = value;
  // @@protoc_insertion_point(field_set:bumoProtocol.WsMessage.sequence)
}

// bytes data = 4;
inline void WsMessage::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WsMessage::data() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.WsMessage.data)
  return data_.GetNoArena();
}
inline void WsMessage::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bumoProtocol.WsMessage.data)
}
#if LANG_CXX11
inline void WsMessage::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bumoProtocol.WsMessage.data)
}
#endif
inline void WsMessage::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bumoProtocol.WsMessage.data)
}
inline void WsMessage::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bumoProtocol.WsMessage.data)
}
inline ::std::string* WsMessage::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:bumoProtocol.WsMessage.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WsMessage::release_data() {
  // @@protoc_insertion_point(field_release:bumoProtocol.WsMessage.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WsMessage::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:bumoProtocol.WsMessage.data)
}

// -------------------------------------------------------------------

// Ping

// int64 nonce = 1;
inline void Ping::clear_nonce() {
  nonce_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Ping::nonce() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.Ping.nonce)
  return nonce_;
}
inline void Ping::set_nonce(::google::protobuf::int64 value) {
  
  nonce_ = value;
  // @@protoc_insertion_point(field_set:bumoProtocol.Ping.nonce)
}

// -------------------------------------------------------------------

// Pong

// int64 nonce = 1;
inline void Pong::clear_nonce() {
  nonce_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Pong::nonce() const {
  // @@protoc_insertion_point(field_get:bumoProtocol.Pong.nonce)
  return nonce_;
}
inline void Pong::set_nonce(::google::protobuf::int64 value) {
  
  nonce_ = value;
  // @@protoc_insertion_point(field_set:bumoProtocol.Pong.nonce)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bumoProtocol

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::bumoProtocol::ERRORCODE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bumoProtocol::ERRORCODE>() {
  return ::bumoProtocol::ERRORCODE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_common_2eproto
